name: Feature request
description: Something ClAudit should do
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do that it does not do
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: How you would want it to work
