name: Feature request
description: Suggest an improvement to ClAudit
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem / use case?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
