#!/usr/bin/env python3
"""Build ONE consolidated, actionable pattern report from everything ClAudit has filed.

113 scattered issues are easy to dismiss as duplicates. A single report that states the root
cause and lists every server-side-lookup-able Request ID, grouped by failure mode, is not.

Reads ~/.claude/claudit/issues.jsonl (the local record of every filed issue) and emits
docs/pattern-report.md — PII-scrubbed, no conversation leadup. Optionally file it as one
tracking issue:  python3 scripts/pattern_report.py --file -R anthropics/claude-code
"""
import argparse
import json
import os
import subprocess
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import claudit_scan as cs   # noqa: E402
from claudit import scrub   # noqa: E402

ISSUES_DB = os.path.expanduser("~/.claude/claudit/issues.jsonl")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "pattern-report.md")

KIND_TITLE = {
    "cyber": "Cybersecurity safety-filter false positives",
    "aup": "AUP / Usage-Policy false positives",
    "harness": "Auto-mode-classifier (harness) denials",
}
KIND_WHAT = {
    "cyber": "In-scope security / administration work pattern-matched on cybersecurity *terminology* "
             "(audit, recovery token, IAM, bypass, credential) with no harmful intent.",
    "aup": "Ordinary, authorized requests flagged as Usage-Policy violations.",
    "harness": "The auto-mode classifier denied authorized actions on the reporter's own systems "
               "(reading a credential from one's own vault, provisioning one's own host, etc.).",
}


def load():
    rows = []
    if os.path.exists(ISSUES_DB):
        for line in open(ISSUES_DB):
            line = line.strip()
            if line:
                try:
                    rows.append(json.loads(line))
                except Exception:
                    pass
    return rows


def build_md(rows):
    by_kind = defaultdict(list)
    for r in rows:
        by_kind[r.get("kind", "other")].append(r)
    all_reqs = sorted({q for r in rows for q in (r.get("reqs") or [])})
    total_issues = len(rows)

    L = []
    L.append("# Pattern: Claude Code classifiers false-positive on authorized administration of "
             "the reporter's OWN infrastructure")
    L.append("")
    L.append(f"_Auto-generated by [ClAudit]({cs.PROJECT_URL}) from {total_issues} filed reports · "
             f"{len(all_reqs)} distinct Request IDs · PII-scrubbed._")
    L.append("")
    L.append("## Root cause (one sentence)")
    L.append("")
    L.append("> The safety / Usage-Policy / auto-mode classifiers cannot distinguish **administering "
             "systems you own and are authorized to operate** from **attacking someone else's** — so "
             "they pattern-match on security *terminology* and block legitimate, in-scope work.")
    L.append("")
    L.append("Every block below stopped authorized work on the reporter's own infrastructure. Each "
             "**Request ID is server-side-lookup-able** — the original prompt can be inspected to "
             "confirm it was benign and in-scope. This is one underlying defect, surfaced across "
             "many surfaces; it is filed as a single report so it can be triaged in one place rather "
             "than closed piecemeal as 'duplicates'.")
    L.append("")
    L.append("## Breakdown by failure mode")
    L.append("")
    L.append("| Kind | Reports | Request IDs | What gets flagged |")
    L.append("|---|---:|---:|---|")
    for kind in ("harness", "cyber", "aup"):
        rs = by_kind.get(kind, [])
        if not rs:
            continue
        nreq = len({q for r in rs for q in (r.get("reqs") or [])})
        L.append(f"| **{kind}** | {len(rs)} | {nreq} | {KIND_WHAT.get(kind, '')} |")
    L.append("")

    for kind in ("harness", "cyber", "aup"):
        rs = by_kind.get(kind, [])
        if not rs:
            continue
        L.append(f"## {KIND_TITLE.get(kind, kind)}")
        L.append("")
        L.append(KIND_WHAT.get(kind, ""))
        L.append("")
        for r in sorted(rs, key=lambda x: x.get("url", "")):
            url = r.get("url", "")
            num = "#" + url.rsplit("/", 1)[-1] if url else "(unfiled)"
            reqs = ", ".join(f"`{q}`" for q in (r.get("reqs") or [])) or "_(no Request ID captured)_"
            L.append(f"- {num} — {reqs}")
        L.append("")

    L.append("## All Request IDs (for server-side lookup)")
    L.append("")
    L.append("```")
    L.extend(all_reqs)
    L.append("```")
    L.append("")
    L.append("## What a fix looks like")
    L.append("")
    L.append("- Treat operations on the user's **own, authorized** infrastructure as in-scope; the "
             "presence of words like *credential, recovery token, IAM, bypass, audit* is not evidence "
             "of an attack.")
    L.append("- When a block fires, surface **why** and a path to proceed for legitimate use — losing "
             "the whole session to a false positive is the core harm.")
    L.append("- Use the Request IDs above to inspect the actual prompts and calibrate the classifiers.")
    L.append("")
    return scrub("\n".join(L))[0]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", action="store_true", help="file the report as one tracking issue")
    ap.add_argument("-R", "--repo", default=cs.DEFAULT_REPO)
    args = ap.parse_args()
    rows = load()
    md = build_md(rows)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(md)
    print(f"wrote {OUT} ({len(rows)} reports)")
    if args.file:
        title = (f"[Tracking] Classifier false-positives on authorized admin of the reporter's own "
                 f"infrastructure — {len({q for r in rows for q in (r.get('reqs') or [])})} Request IDs")
        url = cs.gh_create(args.repo, title, md)
        print("filed:", url)


if __name__ == "__main__":
    main()
